baseURL = "https://bootstrapthemes.netlify.com/"
languageCode = "en-us"
title = "Bootstrap Themes"
theme = "hugo_theme_robust"

[permalinks]
  admin-templates = "/:section/:filename/"
  website-templates = "/:section/:filename/"

[taxonomies]
  tag = "tags"
  category = ""
